apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-170290697
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/user1-tenant/test-app-170290697/java-quarkus-170290697@sha256:efefd21649303e03465b1f4fda712bfdd2ef0c40d3bc811f2a9e4800238bd486
        name: my-java-quarkus
        resources: {}
status: {}
